name: carregar_temas_package
description: Pluguin de carregamento de temas à partir do banco de dados.
version: 1.3.4
homepage: https://github.com/pwlimaverde/carregar_temas_package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  return_success_or_error: ^0.1.7
  flutter:
    sdk: flutter

dev_dependencies:
  rxdart: ^0.26.0-nullsafety.1
  mocktail: ^0.0.1-dev.10
  flutter_test:
    sdk: flutter

flutter: